### ISSUE TITLE
ExtReact doesn't support React Hooks

### ISSUE THREAD

**Issue by ichukanov** [sencha/ext-react#306]
When using a useEffect hook, ExtReact throws the following exception:

Uncaught TypeError: schedulePassiveEffects is not a function
    at react-reconciler.development.js:10938
    at Object.unstable_runWithPriority (scheduler.development.js:255)
    at commitRoot (react-reconciler.development.js:10937)
    at react-reconciler.development.js:12380
    at Object.unstable_runWithPriority (scheduler.development.js:255)
    at completeRoot (react-reconciler.development.js:12379)
    at performWorkOnRoot (react-reconciler.development.js:12308)
    at performWork (react-reconciler.development.js:12216)
    at performSyncWork (react-reconciler.development.js:12190)
    at requestWork (react-reconciler.development.js:12059)

### **example.js**

```
import React, {useEffect} from 'react';
import { Container } from '@sencha/ext-modern';

export default function Example() {
    useEffect(() => {
        console.log("Using React Hook");

    }, []);

  return (
    <Container padding="20">
      <h1>About this App</h1>
      <p>Example</p>
    </Container>
  )
}
```

**Comment by branflake2267** [comment]
Thanks for reporting. One of the team leaders will help out soon.

**Comment by mgusmano** [comment]
this is now fixed in the ext-react-7.0.x branch

**Comment by thomasbrueggemann** [comment]
Is there a roadmap as to when ext-react-7.0.x will be released? The NPM registry currently holds ext-react-6.7.0 packages.
Or is it possible to release a patch for the 6.7.x packages? We would like to use React Hooks with ExtReact!

**Comment by thomasbrueggemann** [comment]
Oh, and the implementation for React Hooks within the Reconciler you used looks identical to: https://github.com/facebook/react/issues/14814#issuecomment-462221984

This code is faulty and the thread over there has progressed to using the `scheduler` module: https://github.com/facebook/react/issues/14814#issuecomment-495341316

**Comment by L3P3** [comment]
We use hooks and ExtReact in production and I hope that it will be implemented properly. Is the flaw pointed out by Thomas sorted out already? I hope to see some more quality in ER 7!

**Comment by L3P3** [comment]
An ugly workaround could also be to just use `useMemo` instead of `useEffect`. This at least works for me for now.

**Comment by thomasbrueggemann** [comment]
@L3P3 You can use `useEffect`, you just have to manually edit the file `node_modules/@sencha/ext-react/dist/ExtRenderer.js` and replace the following code in line 25

```javascript
const ExtRenderer = Reconciler({
```

with

```javascript
const ExtRenderer = Reconciler({
    scheduleDeferredCallback: scheduler.unstable_scheduleCallback,
    cancelDeferredCallback: scheduler.unstable_cancelCallback,
    schedulePassiveEffects: scheduler.unstable_scheduleCallback,
    cancelPassiveEffects: scheduler.unstable_cancelCallback,
```

and add

```javascript
import * as scheduler from "scheduler";
```

to the top of the file.

That is pretty annoying but still less ugly than using `useMemo`.

**Comment by thomasbrueggemann** [comment]
@mgusmano Any news on this one?
